sudo: required

services:
  - docker

notifications:
  email: false

language: python
python:
  - "3.6"

script:
  - pip install --upgrade pip
  - pip install --upgrade codecov
  - make test
  - codecov
