apiVersion: batch/v1
kind: Job
metadata:
  name: green-spider-screenshotter
spec:
  template:
    spec:
      containers:
      - name: screenshotter
        image: quay.io/netzbegruenung/green-spider-screenshotter:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
        resources:
          requests:
            cpu: 800m
            memory: 4000M
      restartPolicy: Never
      volumes:
      - name: secrets
        secret:
          secretName: green-spider
          items:
          - key: datastore-writer.json
            path: datastore-writer.json
          - key: screenshots-uploader.json
            path: screenshots-uploader.json
