apiVersion: batch/v1
kind: Job
metadata:
  name: green-spider-spider
spec:
  parallelism: 1
  template:
    spec:
      containers:
      - name: spider
        image: quay.io/netzbegruenung/green-spider:latest
        imagePullPolicy: Always
        args:
          - "--credentials-path=/secrets/datastore-writer.json"
          - "--loglevel=info"
          - spider
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
        - name: shared
          mountPath: /dev/shm
        resources:
          requests:
            cpu: 900m
            memory: 2000M
      restartPolicy: OnFailure
      volumes:
      - name: secrets
        secret:
          secretName: green-spider
          items:
          - key: datastore-writer.json
            path: datastore-writer.json
      - name: shared
        emptyDir: {}

